package types

type AT_LEAST_NUMBER int

const (
	AT_LEAST_NUMBER_OF_MONTHLY_TASKS AT_LEAST_NUMBER = 8
	AT_LEAST_NUMBER_OF_LONG_TASKS    AT_LEAST_NUMBER = 6

	MAX_CHAR_UNTIL_ELLIPSIS int = 30
	MAX_PER_ROW             int = 2
)
